#! /bin/bash

IMAGE_TAG=latest

function installPanamax {
 if [[ "$1" == "r" ]]; then
   echo "Uninstalling all docker images."
   sudo systemctl stop panamax.service && \
   sudo systemctl disable panamax.service
   sudo rm /etc/systemd/system/panamax.service
   sudo rm /etc/systemd/user/*
   if [[ `docker ps -a -q`  != ""  ]]; then
    echo Found some containers, deleting them.
    sudo docker rm -f `docker ps -a -q`
    sudo docker rmi `docker images -q`
   fi
 fi

 if [[ "$2" == "dev" ]]; then
    IMAGE_TAG=dev
 fi

 echo "Installing Panamax..."
 writeUnitFile
 sudo cp units/* /etc/systemd/system/
 sudo cp scripts/* /etc/systemd/user/

 sudo systemctl enable panamax.service
 sudo systemctl start panamax.service &

 echo "Waiting until Panamax is reassembled"
 waitUntilStarted
 echo "Panamax reassembly complete"
}

function writeUnitFile {
 echo "[Unit]
      Description=Panamax local
      After=docker.service
      Requires=docker.service

      [Service]
      Type=oneshot
      ExecStart=/bin/bash -c '/etc/systemd/user/start_svc.sh $IMAGE_TAG && exit 0'
      ExecStop=/bin/bash -c '/etc/systemd/user/start_svc.sh stop'
      RemainAfterExit=true

      [Install]
      WantedBy=multi-user.target" > units/panamax.service

}

function restartPanamax {
  echo "Restarting Panamax"
  sudo systemctl stop panamax.service
  sudo systemctl start panamax.service
  waitUntilStarted
  echo "Panamax restarted"
}

function stopPanamax {
  echo Stopping Panamax
  sudo systemctl stop panamax.service
  echo Panamax Stopped.
}

function waitUntilStarted {
     logStartTime="`date +'%Y-%m-%d %H:%M:%S'`"
    echo "$logStartTime"
    regex='Panamax setup complete'
    journalctl -u panamax.service --since="$logStartTime" -f | while read line; do
       echo $line
       if [[ $line == *$regex* ]]; then
         pkill -9 -P $$ journalctl
       fi
    done
}

function showHelp {
    echo ""
    echo "Usage:
         ./setup.sh <install/reinstall/restart/stop>
         ./setup.sh "
    echo ""
}

function main {
    operation=$1

    if [[ $# -gt 0 ]]; then
        case $operation in
            install) installPanamax "i" "$2" && exit 0 || { showHelp; exit 1; } ;;
            reinstall) installPanamax "r" "$2" && exit 0 || { showHelp; exit 1; } ;;
            restart) restartPanamax || { showHelp; exit 1; } ;;
            stop) stopPanamax || { showHelp; exit 1; } ;;
            *) showHelp;;
        esac
    else
        echo "Please select one of the following options: "
        select operation in "install" "restart" "reinstall"; do
        case $operation in
            install) installPanamax "i" && exit 0; break;;
            reinstall   ) installPanamax "r" && exit 0; break;;
            restart) restartPanamax; break;;
            stop) stopPanamax; break;;
        esac
        done
    fi
}

main "$@";

