#! /bin/bash

function installPanamax {
 if [[ "$1" -eq "r" ]]; then
   echo "Uninstalling all docker images."
   sudo systemctl stop panamax.service
   sudo systemctl disable panamax.service
   if [[ `docker ps -a -q`  != ""  ]]; then
    echo Found some containers, deleting them.
    sudo docker rm -f `docker ps -a -q`
    sudo docker rmi `docker images -a -q`
   fi
 fi

 echo "Installing Panamax..."
 cp units/* /etc/systemd/system/
 cp -R scripts/* /etc/systemd/user/

 sudo systemctl enable panamax.service
 sudo systemctl start panamax.service

 echo Waiting until Panamax is reassembled
 waitUntilStarted
 echo Panamax reassembly complete
 exit 0
}

function restartPanamax {
  echo Restarting Panamax
  sudo systemctl stop panamax.service
  sudo systemctl start panamax.service
  waitUntilStarted
  echo Panamax restarted
  exit 0
}

function waitUntilStarted {
    regex='Panamax setup complete'
    journalctl -u panamax.service -f | while read line; do
       echo $line
       if [[ $line == *$regex* ]]; then
         pkill -9 -P $$ journalctl
       fi
    done
}

function showHelp {
    echo ""
    echo "Usage:
         ./setup.sh <install/reinstall/restart>
         ./setup.sh "
    echo ""
}

function main {
    operation=$1

    if [[ $# -gt 0 ]]; then
        case $operation in
            install) installPanamax "i" || { showHelp; exit 1; } ;;
            reinstall) installPanamax "r" || { showHelp; exit 1; } ;;
            restart) restartPanamax;;
            *) showHelp;;
        esac
    else
        echo "Please select one of the following options: "
        select operation in "install" "restart" "reinstall"; do
        case $operation in
            install) installPanamax "i"; break;;
            reinstall   ) installPanamax "r"; break;;
            restart) restartPanamax; break;;
        esac
        done
    fi

}

main "$@";
